Add location manager
UIUC-PPL/charmlite pull request #18
Opened 2022-01-07 01:16 UTC by adityapb

- [ ] Add location manager to keep track of locations of home elements
- [ ] Add a `pe` option to `element_proxy::insert` to allow inserting elements on a user specified pe
- [ ] Add a routing cache to keep track of locations of elements previously communicated with
- [ ] Get bcasts and reductions to work with the location manager

2022-01-07 02:30 UTC, jszaday reviewed
This looks quite promising! It's wonderful to start seeing these more conventional Charm-ism blend in.

I know this is a draft, but there are a few things I wanted to bring to your attention. If they're things you were already planning to do, please consider my comments as affirmation.

2022-01-07 02:30 UTC, jszaday commented on include/charmlite/core/collection.hpp
> +        send_location_update_(chare_index_t idx, int home_pe, int loc)
These can be moved into the `collection_bridge_`, since it's meant to encapsulate type-specific behaviors.

2022-01-07 02:30 UTC, jszaday commented on include/charmlite/core/destination.hpp
> +            int pe;
In the model of Converse, messages are only assigned a PE at the callsite of `send`. We can overload the function with an alternative that enforces a specific destination PE, and avoid adding this to the header. `insert` can use this to route it directly to the desired PE.

In Charm++, there are two types of array element creation messages: `createhere` or `createhome`. If a PE receives a `createhere` message, it creates it regardless of whether it's its home. We can replicate this behavior here with a boolean flag in the message.

2022-01-07 02:30 UTC, jszaday commented on include/charmlite/core/message.hpp
> +        static constexpr auto for_location_update_ = for_collection_ + 1;
`for_collection` is intended to encapsulate this behavior; please do not reserve a separate flag.

2022-01-07 02:30 UTC, jszaday commented on include/charmlite/core/collection_bridge.hpp
> +            this->locmgr_.update_location(idx, pe);
Please move the logic for flushing the buffers here.

2022-01-07 02:30 UTC, jszaday commented on include/charmlite/core/collection.hpp
> +            auto home_pe = this->locmgr_.pe_for(idx);
A few things:
1. This should be something more like "if (createhere || homePe(idx) == myPe)"
2. You can change the name of the existing `pe_for` method to `home_pe`, then add `lookup` which reports the last known location. Then it'll match Charm++ :)
3. When you do that, refactor the parts of the code that use `pe_for` to use the right method. Most should change to `lookup`.
4. For node/group locmgrs, `lookup` will be the same as `home_pe`.

2022-01-08 18:22 UTC, jszaday commented
> Ah yes, got it. I think I will still need a `sender_pe` member in `message` to get the original sender's PE for sending a routing update back. I will probably also need another flag to mark if a message was forwarded at least once to avoid sending a routing update if the cache on the sender PE pointed to the correct location.

Right, right. Those should be fine. Be sure to add them to both the `message` and `message_fields` structs so the alignment properties are preserved.

2022-01-14 20:34 UTC, adityapb commented
This is ready for review now

2022-01-15 00:03 UTC, jszaday commented on include/charmlite/core/collection.hpp
> +                    if (this->locmgr_.lookup(view) == CmiMyPe())
This should be a "home_pe" operation.

2022-01-15 00:12 UTC, jszaday requested changes
Looks pretty much there now! One minor thing to fix.

2022-01-15 00:19 UTC, adityapb commented
> Looks pretty much there now! One minor thing to fix.

Done!

2022-01-15 01:19 UTC, merged